### ISSUE TITLE
npm run stargazer:init ⟶ "sh: stargazer:init: command not found"

### ISSUE THREAD

**Issue by chadlavi-casebook** [tenx-tech/stargazer#18]
I'm following the quickstart instructions, and it seems there's an error here with the npm scripts.

 When I run `npm run stargazer:init` I get this error: 

```
> [myappname]@6.0.0-alpha.1 stargazer:init /Users/[me]/[app-dir]
> stargazer:init

sh: stargazer:init: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! [myappname]@6.0.0-alpha.1 stargazer:init: `stargazer:init`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the [myappname]@6.0.0-alpha.1 stargazer:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/[me]/.npm/_logs/2020-03-06T20_28_26_617Z-debug.log
```

the contents of that log file:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/13.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'stargazer:init'
1 verbose cli ]
2 info using npm@6.13.6
3 info using node@v13.7.0
4 verbose run-script [ 'prestargazer:init', 'stargazer:init', 'poststargazer:init' ]
5 info lifecycle [myappname]@6.0.0-alpha.1~prestargazer:init: [myappname]@6.0.0-alpha.1
6 info lifecycle [myappname]@6.0.0-alpha.1~stargazer:init: [myappname]@6.0.0-alpha.1
7 verbose lifecycle [myappname]@6.0.0-alpha.1~stargazer:init: unsafe-perm in lifecycle true
8 verbose lifecycle [myappname]@6.0.0-alpha.1~stargazer:init: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/[me]/[app-dir]/node_modules/.bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/[me]/.rvm/bin:/usr/local/Cellar/yvm/3.6.6/shim:/Users/[me]/Library/Android/sdk/emulator:/Users/[me]/Library/Android/sdk/tools:/Users/[me]/Library/Android/sdk/tools/bin:/Users/[me]/Library/Android/sdk/platform-tools
9 verbose lifecycle [myappname]@6.0.0-alpha.1~stargazer:init: CWD: /Users/[me]/[app-dir]
10 silly lifecycle [myappname]@6.0.0-alpha.1~stargazer:init: Args: [ '-c', 'stargazer:init' ]
11 info lifecycle [myappname]@6.0.0-alpha.1~stargazer:init: Failed to exec stargazer:init script
12 verbose stack Error: [myappname]@6.0.0-alpha.1 stargazer:init: `stargazer:init`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:321:20)
12 verbose stack     at maybeClose (internal/child_process.js:1026:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid [myappname]@6.0.0-alpha.1
14 verbose cwd /Users/[me]/[app-dir]
15 verbose Darwin 19.3.0
16 verbose argv "/usr/local/Cellar/node/13.7.0/bin/node" "/usr/local/bin/npm" "run" "stargazer:init"
17 verbose node v13.7.0
18 verbose npm  v6.13.6
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error [myappname]@6.0.0-alpha.1 stargazer:init: `stargazer:init`
23 error spawn ENOENT
24 error Failed at the [myappname]@6.0.0-alpha.1 stargazer:init script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

**Comment by AudyOdi** [comment]
Hi there,

Thank you for having interest in the Stargazer project. Unfortunately, we couldn’t maintain the project anymore as we have shifted our tech stack and we don’t have the resources for the task. For any further developments, please feel free to fork the repo and create your own version of Stargazer.

Once again, thank you for the interest in this project. Feel free to reach out to the organization for any questions.
